name: Build

#on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
on:
  push:
    branches: [ "master" ]
  #schedule:
   # - cron: '0 9 * * 5' # every Friday at 17:00pm UTC+8
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: NASM
        uses: ilammy/setup-nasm@v1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.1
      - name: Install dependencies
        run: npm install
        working-directory: ${{ github.workspace }}/project
      - name: Build project
        run: npm run build:release
        working-directory: ${{ github.workspace }}/project
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'Server-${{ steps.date.outputs.date }}.zip'
          directory: 'project/build/'
          exclusions: '*.git* /*node_modules/* .editorconfig'
 
      - name: Upload files to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          files: project/build/Server-${{ steps.date.outputs.date }}.zip
          tag_name: HappyWeekend
          name: 这里下载
      #- name: Upload file to webdav
       # uses: bxb100/action-upload@main
        #with:
          #webdav_address: ${{secrets.CT_ADDRESS}}
          #webdav_username: ${{secrets.CT_EMAIL}}
          #webdav_password: ${{secrets.CT_PASSWORD}}
          #webdav_upload_path: "/AkiBE"
          #files: "project/Dockerfile"
         # provider: webdav
        #  provider_options: |
      #      endpoint=${{ secrets.CT_ADDRESS }}
      #      username=${{ secrets.CT_EMAIL }}
      #      password=${{ secrets.CT_PASSWORD }}
      #      root=/test/
      #    include: 'project/build/**'
